name: CI Test
on: [push, pull_request]
jobs:
  run_tests:
    name: Run Tests
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: ./.github/bin/test.sh
        env:
          DESTINATION: OS=12.2,name=iPhone X
          SCHEME: WebP iOS
          SDK: iphonesimulator12.2
          WORKSPACE: WebP.xcworkspace
